### ISSUE TITLE
cloud formation fails to deploy - ExampleC9BootstrapInstanceLambda timeout

### ISSUE THREAD

**Issue by seaphu** [aws-samples/aws-cloud9-bootstrapping-example#9] opened 2024-09-29 13:35 UTC
**Describe the bug**
When deploying this could formation I get the following error after a long 15 minute+ wait. 
for ExampleC9BootstrapInstanceLambda:  CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [***-***-***]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

**To Reproduce**
1. run example_setup.sh (in us-west-2)
2. wait for cloudformation stack to fail and rollback
3. view stack events for detailed error message (also copied above)

**Expected behavior**
stack deployment should succeed without error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: amazon linux 2023
 
**Additional context**
cfn stack times out on deployment and then fails.

**Comment by couchgott** [comment] 2024-09-30 08:09
taking a look within the next days. 

best,

David

**Comment by couchgott** [comment] 2024-10-01 11:09
hey @seaphu , 

i basically could not restore the behaviour you ran into in us-west-2. 
can you help me and look into your cloudwatch logs and pull out the logs written by the Lambda-function doing the boostrap? 
i did also update the python runtime to the most current python3 version just in case :) 

Ty! 

David

**Comment by cszhz** [comment] 2024-10-09 06:06
+1  I met error as well.
ExampleC9BootstrapInstanceLambda
```
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [a863efff-ffb8-49e7-b37c-254770211ceb]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
```

**Comment by couchgott** [comment] 2024-10-09 09:41
hi @cszhz ,

can you be so kind and add the AWS Lambda function output you get into the ticket? 

Ty!

David

**Comment by cszhz** [comment] 2024-10-09 16:07
Hi David,
Thanks for your advice.
The root cause is  missing statement between if else (example_instancestack.yaml  line 202-203), I added "pass", the lambda error disappear.

However cloud9 disk resize is still not success. So far there are two OS selection in cloud9 :amazon linux 2 and amazon linux 2023.
i added the following statement, but it is no effect.
```
SUBAL2023="VERSION_ID=\"2023\""
                if [[ "$STR" == *"$SUBAL2"* || "$STR" == *"$SUBAL2023"* ]]
```
https://docs.aws.amazon.com/zh_cn/cloud9/latest/user-guide/move-environment.html#move-environment-resize

Could you please take a look? Have a nice day.

**Comment by couchgott** [comment] 2024-11-14 18:37
Hey, 

i am working on this right now. I did a full rewrite of the Lambda function and the Automation document. 
While it is functional by itself i am still challaging some permission issues causing the process being unable to read out the needed volumeID. but that's what i am debugging right now. 

feel free to give it a try.

**Comment by couchgott** [comment] 2024-11-14 19:57
i consider this resolved with the latest version.

**Closed as completed by couchgott** 2024-11-14 19:57 UTC
Labels: bug
